language: node_js
node_js: node
cache: npm

# create a production build
script:
- npm run build

before_deploy:
# extract the deploy_rsa to the /tmp folder to avoid deploying the decrypted key
- openssl aes-256-cbc -K $encrypted_1297b3b420ca_key -iv $encrypted_1297b3b420ca_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
# add the key to the ssh-agent to make any SSH command agnostic to the private key location
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

# deployment via the travis build, see this for details:
# https://oncletom.io/2016/travis-ssh-deploy/
addons:
  ssh_known_hosts: d11n.net
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
